// flow-typed signature: 0d59cb5dbf283e3a25dcd194ef922f41
// flow-typed version: <<STUB>>/@apptoms/core_v^0.0.0/flow_v0.67.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@apptoms/core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@apptoms/core' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@apptoms/core/babel.config' {
  declare module.exports: any;
}

declare module '@apptoms/core/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module '@apptoms/core/flow-typed/npm/jest_v23.x.x' {
  declare module.exports: any;
}

declare module '@apptoms/core/flow-typed/npm/jest-cli_vx.x.x' {
  declare module.exports: any;
}

declare module '@apptoms/core/flow-typed/npm/prettier_v1.x.x' {
  declare module.exports: any;
}

declare module '@apptoms/core/src/index' {
  declare module.exports: any;
}

declare module '@apptoms/core/src/system/flex' {
  declare module.exports: any;
}

declare module '@apptoms/core/src/system/index' {
  declare module.exports: any;
}

declare module '@apptoms/core/src/system/size' {
  declare module.exports: any;
}

declare module '@apptoms/core/src/system/spacing' {
  declare module.exports: any;
}

declare module '@apptoms/core/src/system/text' {
  declare module.exports: any;
}

declare module '@apptoms/core/src/system/theme' {
  declare module.exports: any;
}

declare module '@apptoms/core/src/theme.legacy/defaultTheme' {
  declare module.exports: any;
}

declare module '@apptoms/core/src/theme.legacy/index' {
  declare module.exports: any;
}

declare module '@apptoms/core/src/theme.legacy/theme' {
  declare module.exports: any;
}

declare module '@apptoms/core/src/theme.legacy/theme.test' {
  declare module.exports: any;
}

declare module '@apptoms/core/src/theme.legacy/ThemeError' {
  declare module.exports: any;
}

declare module '@apptoms/core/src/theme.legacy/types' {
  declare module.exports: any;
}

declare module '@apptoms/core/src/theme.legacy/utils' {
  declare module.exports: any;
}

declare module '@apptoms/core/src/theme/theme' {
  declare module.exports: any;
}

declare module '@apptoms/core/src/theme/theme.test' {
  declare module.exports: any;
}

declare module '@apptoms/core/src/types' {
  declare module.exports: any;
}

// Filename aliases
declare module '@apptoms/core/babel.config.js' {
  declare module.exports: $Exports<'@apptoms/core/babel.config'>;
}
declare module '@apptoms/core/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'@apptoms/core/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module '@apptoms/core/flow-typed/npm/jest_v23.x.x.js' {
  declare module.exports: $Exports<'@apptoms/core/flow-typed/npm/jest_v23.x.x'>;
}
declare module '@apptoms/core/flow-typed/npm/jest-cli_vx.x.x.js' {
  declare module.exports: $Exports<'@apptoms/core/flow-typed/npm/jest-cli_vx.x.x'>;
}
declare module '@apptoms/core/flow-typed/npm/prettier_v1.x.x.js' {
  declare module.exports: $Exports<'@apptoms/core/flow-typed/npm/prettier_v1.x.x'>;
}
declare module '@apptoms/core/src/index.js' {
  declare module.exports: $Exports<'@apptoms/core/src/index'>;
}
declare module '@apptoms/core/src/system/flex.js' {
  declare module.exports: $Exports<'@apptoms/core/src/system/flex'>;
}
declare module '@apptoms/core/src/system/index.js' {
  declare module.exports: $Exports<'@apptoms/core/src/system/index'>;
}
declare module '@apptoms/core/src/system/size.js' {
  declare module.exports: $Exports<'@apptoms/core/src/system/size'>;
}
declare module '@apptoms/core/src/system/spacing.js' {
  declare module.exports: $Exports<'@apptoms/core/src/system/spacing'>;
}
declare module '@apptoms/core/src/system/text.js' {
  declare module.exports: $Exports<'@apptoms/core/src/system/text'>;
}
declare module '@apptoms/core/src/system/theme.js' {
  declare module.exports: $Exports<'@apptoms/core/src/system/theme'>;
}
declare module '@apptoms/core/src/theme.legacy/defaultTheme.js' {
  declare module.exports: $Exports<'@apptoms/core/src/theme.legacy/defaultTheme'>;
}
declare module '@apptoms/core/src/theme.legacy/index.js' {
  declare module.exports: $Exports<'@apptoms/core/src/theme.legacy/index'>;
}
declare module '@apptoms/core/src/theme.legacy/theme.js' {
  declare module.exports: $Exports<'@apptoms/core/src/theme.legacy/theme'>;
}
declare module '@apptoms/core/src/theme.legacy/theme.test.js' {
  declare module.exports: $Exports<'@apptoms/core/src/theme.legacy/theme.test'>;
}
declare module '@apptoms/core/src/theme.legacy/ThemeError.js' {
  declare module.exports: $Exports<'@apptoms/core/src/theme.legacy/ThemeError'>;
}
declare module '@apptoms/core/src/theme.legacy/types.js' {
  declare module.exports: $Exports<'@apptoms/core/src/theme.legacy/types'>;
}
declare module '@apptoms/core/src/theme.legacy/utils.js' {
  declare module.exports: $Exports<'@apptoms/core/src/theme.legacy/utils'>;
}
declare module '@apptoms/core/src/theme/theme.js' {
  declare module.exports: $Exports<'@apptoms/core/src/theme/theme'>;
}
declare module '@apptoms/core/src/theme/theme.test.js' {
  declare module.exports: $Exports<'@apptoms/core/src/theme/theme.test'>;
}
declare module '@apptoms/core/src/types.js' {
  declare module.exports: $Exports<'@apptoms/core/src/types'>;
}
