// flow-typed signature: e7408db40e1145bbec68469100a95605
// flow-typed version: <<STUB>>/create-react-context_v0.2.3/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'create-react-context'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'create-react-context' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'create-react-context/lib/implementation' {
  declare module.exports: any;
}

declare module 'create-react-context/lib/index' {
  declare module.exports: any;
}

declare module 'create-react-context/lib/maxSigned31BitInt' {
  declare module.exports: any;
}

// Filename aliases
declare module 'create-react-context/lib/implementation.js' {
  declare module.exports: $Exports<'create-react-context/lib/implementation'>;
}
declare module 'create-react-context/lib/index.js' {
  declare module.exports: $Exports<'create-react-context/lib/index'>;
}
declare module 'create-react-context/lib/maxSigned31BitInt.js' {
  declare module.exports: $Exports<'create-react-context/lib/maxSigned31BitInt'>;
}
